sudo: false
language: minimal
addons:
  apt:
    packages:
      - freebsd-glue
      - original-awk
      - zsh
env:
  matrix:
    - ESH_SHELL="/bin/busybox ash" ESH_AWK="/bin/busybox awk"
    - ESH_SHELL="/bin/dash"
    - ESH_SHELL="/bin/bash"
    - ESH_SHELL="/bin/zsh5"
    - ESH_AWK="/usr/bin/original-awk"
    - ESH_AWK="/usr/lib/freebsd/awk"
script:
  - ESH="$ESH_SHELL $(pwd)/esh" make test
